# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-4.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-4.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-4.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Antoine/Desktop/ProjetMeanBean/DrRob

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Antoine/Desktop/ProjetMeanBean/DrRob

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-4.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-4.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Antoine/Desktop/ProjetMeanBean/DrRob/CMakeFiles /Users/Antoine/Desktop/ProjetMeanBean/DrRob/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Antoine/Desktop/ProjetMeanBean/DrRob/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DrRob

# Build rule for target.
DrRob: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DrRob
.PHONY : DrRob

# fast build rule for target.
DrRob/fast:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/build
.PHONY : DrRob/fast

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/main.s
.PHONY : main.s

# target to build an object file
source/DashBoard.o:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/DashBoard.o
.PHONY : source/DashBoard.o

# target to preprocess a source file
source/DashBoard.i:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/DashBoard.i
.PHONY : source/DashBoard.i

# target to generate assembly for a file
source/DashBoard.s:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/DashBoard.s
.PHONY : source/DashBoard.s

# target to build an object file
source/Game.o:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/Game.o
.PHONY : source/Game.o

# target to preprocess a source file
source/Game.i:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/Game.i
.PHONY : source/Game.i

# target to generate assembly for a file
source/Game.s:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/Game.s
.PHONY : source/Game.s

# target to build an object file
source/Grille.o:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/Grille.o
.PHONY : source/Grille.o

# target to preprocess a source file
source/Grille.i:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/Grille.i
.PHONY : source/Grille.i

# target to generate assembly for a file
source/Grille.s:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/Grille.s
.PHONY : source/Grille.s

# target to build an object file
source/InterfaceX.o:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/InterfaceX.o
.PHONY : source/InterfaceX.o

# target to preprocess a source file
source/InterfaceX.i:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/InterfaceX.i
.PHONY : source/InterfaceX.i

# target to generate assembly for a file
source/InterfaceX.s:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/InterfaceX.s
.PHONY : source/InterfaceX.s

# target to build an object file
source/MoteurPhy.o:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/MoteurPhy.o
.PHONY : source/MoteurPhy.o

# target to preprocess a source file
source/MoteurPhy.i:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/MoteurPhy.i
.PHONY : source/MoteurPhy.i

# target to generate assembly for a file
source/MoteurPhy.s:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/MoteurPhy.s
.PHONY : source/MoteurPhy.s

# target to build an object file
source/SDL_rotozoom.o:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/SDL_rotozoom.o
.PHONY : source/SDL_rotozoom.o

# target to preprocess a source file
source/SDL_rotozoom.i:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/SDL_rotozoom.i
.PHONY : source/SDL_rotozoom.i

# target to generate assembly for a file
source/SDL_rotozoom.s:
	$(MAKE) -f CMakeFiles/DrRob.dir/build.make CMakeFiles/DrRob.dir/source/SDL_rotozoom.s
.PHONY : source/SDL_rotozoom.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DrRob"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/DashBoard.o"
	@echo "... source/DashBoard.i"
	@echo "... source/DashBoard.s"
	@echo "... source/Game.o"
	@echo "... source/Game.i"
	@echo "... source/Game.s"
	@echo "... source/Grille.o"
	@echo "... source/Grille.i"
	@echo "... source/Grille.s"
	@echo "... source/InterfaceX.o"
	@echo "... source/InterfaceX.i"
	@echo "... source/InterfaceX.s"
	@echo "... source/MoteurPhy.o"
	@echo "... source/MoteurPhy.i"
	@echo "... source/MoteurPhy.s"
	@echo "... source/SDL_rotozoom.o"
	@echo "... source/SDL_rotozoom.i"
	@echo "... source/SDL_rotozoom.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

