.TH "include/Color.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Color.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE_COLOR\fP   7"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBColor\fP { \fBRED\fP = 0, \fBBLUE\fP, \fBYELLOW\fP, \fBGREEN\fP, \fBPURPLE\fP, \fBDARK\fP, \fBBLANK\fP }"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define SIZE_COLOR   7"
.PP
Définition à la ligne 3 du fichier Color.h.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBColor\fP"
.PP
\fBValeurs énumérées: \fP
.in +1c
.TP
\fB\fIRED \fP\fP
.TP
\fB\fIBLUE \fP\fP
.TP
\fB\fIYELLOW \fP\fP
.TP
\fB\fIGREEN \fP\fP
.TP
\fB\fIPURPLE \fP\fP
.TP
\fB\fIDARK \fP\fP
.TP
\fB\fIBLANK \fP\fP

.PP
Définition à la ligne 4 du fichier Color.h.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
