.TH "ConnectedComponents" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectedComponents \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <conected.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSimilarity\fP"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBConnectedComponents\fP (int soft_maxlabels)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "template<class Tin , class Tlabel , class Comparator , class Boolean > int \fBconnected\fP (const Tin *img, Tlabel *out, int width, int height, Comparator, Boolean K8_connectivity)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 24 du fichier conected.h.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "ConnectedComponents::ConnectedComponents (intsoft_maxlabels)\fC [inline]\fP"
.PP
Définition à la ligne 27 du fichier conected.h.
.SH "Documentation des fonctions membres"
.PP 
.SS "void ConnectedComponents::clear ()\fC [inline]\fP"
.PP
Définition à la ligne 30 du fichier conected.h.
.SS "template<class Tin , class Tlabel , class Comparator , class Boolean > int ConnectedComponents::connected (const Tin *img, Tlabel *out, intwidth, intheight, ComparatorSAME, BooleanK8_connectivity)"
.PP
Définition à la ligne 97 du fichier conected.h.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
