.TH "constant" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constant \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <conected.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBoperator T\fP () const "
.br
.in -1c
.SH "Description détaillée"
.PP 

.SS "template<class T, T V>struct constant< T, V >"

.PP
Définition à la ligne 18 du fichier conected.h.
.SH "Documentation des fonctions membres"
.PP 
.SS "template<class T , T V> \fBconstant\fP< T, V >::operator T () const\fC [inline]\fP"
.PP
Définition à la ligne 20 du fichier conected.h.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
