.TH "include/Controls.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Controls.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE_COMMANDS\fP   5"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBControls\fP { \fBCGAUCHE\fP = 0, \fBCDROITE\fP, \fBCBAS\fP, \fBCHORAIRE\fP, \fBCANTIHORAIRE\fP }"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define SIZE_COMMANDS   5"
.PP
Définition à la ligne 3 du fichier Controls.h.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBControls\fP"
.PP
\fBValeurs énumérées: \fP
.in +1c
.TP
\fB\fICGAUCHE \fP\fP
.TP
\fB\fICDROITE \fP\fP
.TP
\fB\fICBAS \fP\fP
.TP
\fB\fICHORAIRE \fP\fP
.TP
\fB\fICANTIHORAIRE \fP\fP

.PP
Définition à la ligne 4 du fichier Controls.h.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
