.TH "include/Game.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Game.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Controls.h'\fP
.br
\fC#include 'Blobs.h'\fP
.br
\fC#include 'MoteurPhy.h'\fP
.br
\fC#include 'DashBoard.h'\fP
.br
\fC#include 'Clock.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <list>\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include 'InterfaceX.h'\fP
.br
\fC#include 'Easy.h'\fP
.br
\fC#include 'Hard.h'\fP
.br
\fC#include 'Joueur.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
