.TH "include/InterfaceX.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/InterfaceX.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDL.h>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <SDL_image.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <SDL_ttf.h>\fP
.br
\fC#include 'SDL_rotozoom.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Position.h'\fP
.br
\fC#include 'DashBoard.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'Color.h'\fP
.br
\fC#include 'Link.h'\fP
.br
\fC#include 'State.h'\fP
.br
\fC#include 'Blobs.h'\fP
.br
\fC#include <time.h>\fP
.br
\fC#include 'Clock.h'\fP
.br
\fC#include 'Controls.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInterfaceX\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGetCurrentDir\fP   getcwd"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define GetCurrentDir   getcwd"
.PP
Définition à la ligne 25 du fichier InterfaceX.h.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
