.TH "Joueur" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Joueur \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Joueur.h>\fP
.PP
Est dérivée de \fBDashBoard\fP.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBJoueur\fP (int taille, \fBGrille\fP *grille, std::list< \fBBlobs\fP > *randBlobs)"
.br
.ti -1c
.RI "virtual \fB~Joueur\fP ()"
.br
.ti -1c
.RI "virtual void \fBthink\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 6 du fichier Joueur.h.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Joueur::Joueur (inttaille, \fBGrille\fP *grille, std::list< \fBBlobs\fP > *randBlobs)\fC [inline]\fP"
.PP
Définition à la ligne 9 du fichier Joueur.h.
.SS "virtual Joueur::~Joueur ()\fC [inline, virtual]\fP"
.PP
Définition à la ligne 11 du fichier Joueur.h.
.SH "Documentation des fonctions membres"
.PP 
.SS "virtual void Joueur::think ()\fC [inline, virtual]\fP"
.PP
Implémente \fBDashBoard\fP.
.PP
Définition à la ligne 13 du fichier Joueur.h.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
