.TH "include/Link.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Link.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE_LINK\fP   16"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBLink\fP { \fBNO_LINK\fP = 0, \fBS\fP, \fBN\fP, \fBSN\fP, \fBE\fP, \fBSE\fP, \fBNE\fP, \fBSEN\fP, \fBW\fP, \fBSW\fP, \fBWN\fP, \fBWNS\fP, \fBEW\fP, \fBEWS\fP, \fBEWN\fP, \fBSEWN\fP }"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define SIZE_LINK   16"
.PP
Définition à la ligne 3 du fichier Link.h.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBLink\fP"
.PP
\fBValeurs énumérées: \fP
.in +1c
.TP
\fB\fINO_LINK \fP\fP
.TP
\fB\fIS \fP\fP
.TP
\fB\fIN \fP\fP
.TP
\fB\fISN \fP\fP
.TP
\fB\fIE \fP\fP
.TP
\fB\fISE \fP\fP
.TP
\fB\fINE \fP\fP
.TP
\fB\fISEN \fP\fP
.TP
\fB\fIW \fP\fP
.TP
\fB\fISW \fP\fP
.TP
\fB\fIWN \fP\fP
.TP
\fB\fIWNS \fP\fP
.TP
\fB\fIEW \fP\fP
.TP
\fB\fIEWS \fP\fP
.TP
\fB\fIEWN \fP\fP
.TP
\fB\fISEWN \fP\fP

.PP
Définition à la ligne 7 du fichier Link.h.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
