.TH "include/MoteurPhy.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MoteurPhy.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'Position.h'\fP
.br
\fC#include 'Grille.h'\fP
.br
\fC#include 'Tree.h'\fP
.br
\fC#include 'conected.h'\fP
.br
\fC#include 'Blobs.h'\fP
.br
\fC#include 'Orientation.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <set>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMoteurPhy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOUCHING_ANIM_TIME\fP   6"
.br
.ti -1c
.RI "#define \fBFALLING_ANIM_TIME\fP   0"
.br
.ti -1c
.RI "#define \fBCOMBOTING_ANIM_TIME\fP   120"
.br
.ti -1c
.RI "#define \fBTURNING_ANIM_TIME\fP   6"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define COMBOTING_ANIM_TIME   120"
.PP
Définition à la ligne 7 du fichier MoteurPhy.h.
.SS "#define FALLING_ANIM_TIME   0"
.PP
Définition à la ligne 6 du fichier MoteurPhy.h.
.SS "#define TOUCHING_ANIM_TIME   6"
.PP
Définition à la ligne 5 du fichier MoteurPhy.h.
.SS "#define TURNING_ANIM_TIME   6"
.PP
Définition à la ligne 8 du fichier MoteurPhy.h.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
