.TH "include/Orientation.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Orientation.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBOrientation\fP { \fBHAUT\fP, \fBBAS\fP, \fBDROITE\fP, \fBGAUCHE\fP }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBOrientation\fP"
.PP
\fBValeurs énumérées: \fP
.in +1c
.TP
\fB\fIHAUT \fP\fP
.TP
\fB\fIBAS \fP\fP
.TP
\fB\fIDROITE \fP\fP
.TP
\fB\fIGAUCHE \fP\fP

.PP
Définition à la ligne 4 du fichier Orientation.h.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
