.TH "Position" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Position \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Position.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBPosition\fP (int x, int y)"
.br
.ti -1c
.RI "\fBPosition\fP ()"
.br
.ti -1c
.RI "\fB~Position\fP ()"
.br
.ti -1c
.RI "const int \fBx\fP () const "
.br
.ti -1c
.RI "const int \fBy\fP () const "
.br
.ti -1c
.RI "void \fBsetX\fP (int x)"
.br
.ti -1c
.RI "void \fBsetY\fP (int y)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "int \fB_x\fP"
.br
.ti -1c
.RI "int \fB_y\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 4 du fichier Position.h.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Position::Position (intx, inty)\fC [inline]\fP"
.PP
Définition à la ligne 12 du fichier Position.h.
.SS "Position::Position ()\fC [inline]\fP"
.PP
Définition à la ligne 13 du fichier Position.h.
.SS "Position::~Position ()\fC [inline]\fP"
.PP
Définition à la ligne 14 du fichier Position.h.
.SH "Documentation des fonctions membres"
.PP 
.SS "void Position::setX (intx)\fC [inline]\fP"
.PP
Définition à la ligne 23 du fichier Position.h.
.SS "void Position::setY (inty)\fC [inline]\fP"
.PP
Définition à la ligne 24 du fichier Position.h.
.SS "const int Position::x () const\fC [inline]\fP"
.PP
Définition à la ligne 15 du fichier Position.h.
.SS "const int Position::y () const\fC [inline]\fP"
.PP
Définition à la ligne 19 du fichier Position.h.
.SH "Documentation des données membres"
.PP 
.SS "int \fBPosition::_x\fP\fC [protected]\fP"
.PP
Définition à la ligne 8 du fichier Position.h.
.SS "int \fBPosition::_y\fP\fC [protected]\fP"
.PP
Définition à la ligne 9 du fichier Position.h.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
