.TH "include/State.h" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/State.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBFIXED\fP, \fBCOMBOTING\fP, \fBFALLING\fP, \fBLANDING\fP, \fBCURRENT\fP, \fBPIVOT\fP, \fBFALLIN_ANIM\fP, \fBNO_STATE\fP }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBState\fP"
.PP
\fBValeurs énumérées: \fP
.in +1c
.TP
\fB\fIFIXED \fP\fP
.TP
\fB\fICOMBOTING \fP\fP
.TP
\fB\fIFALLING \fP\fP
.TP
\fB\fILANDING \fP\fP
.TP
\fB\fICURRENT \fP\fP
.TP
\fB\fIPIVOT \fP\fP
.TP
\fB\fIFALLIN_ANIM \fP\fP
.TP
\fB\fINO_STATE \fP\fP

.PP
Définition à la ligne 4 du fichier State.h.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
