.TH "tColorY" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tColorY \- 
.PP
A 8bit Y/palette pixel.  

.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "Uint8 \fBy\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
A 8bit Y/palette pixel. 
.PP
Définition à la ligne 33 du fichier SDL_rotozoom.c.
.SH "Documentation des données membres"
.PP 
.SS "Uint8 \fBtColorY::y\fP"
.PP
Définition à la ligne 34 du fichier SDL_rotozoom.c.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
