.TH "tColorRGBA" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tColorRGBA \- 
.PP
A 32 bit RGBA pixel.  

.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "Uint8 \fBr\fP"
.br
.ti -1c
.RI "Uint8 \fBg\fP"
.br
.ti -1c
.RI "Uint8 \fBb\fP"
.br
.ti -1c
.RI "Uint8 \fBa\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
A 32 bit RGBA pixel. 
.PP
Définition à la ligne 23 du fichier SDL_rotozoom.c.
.SH "Documentation des données membres"
.PP 
.SS "Uint8 \fBtColorRGBA::a\fP"
.PP
Définition à la ligne 27 du fichier SDL_rotozoom.c.
.SS "Uint8 \fBtColorRGBA::b\fP"
.PP
Définition à la ligne 26 du fichier SDL_rotozoom.c.
.SS "Uint8 \fBtColorRGBA::g\fP"
.PP
Définition à la ligne 25 du fichier SDL_rotozoom.c.
.SS "Uint8 \fBtColorRGBA::r\fP"
.PP
Définition à la ligne 24 du fichier SDL_rotozoom.c.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
