.TH "Tree" 3 "Mon May 9 2011" "Version 1.0" "Dr.Robotnik Mean Bean Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tree \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tree.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBTree\fP (X data)"
.br
.ti -1c
.RI "\fB~Tree\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "X \fB_data\fP"
.br
.ti -1c
.RI "\fBTree\fP * \fB_fils_gauche\fP"
.br
.ti -1c
.RI "\fBTree\fP * \fB_fils_droit\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 

.SS "template<typename X>class Tree< X >"

.PP
Définition à la ligne 6 du fichier Tree.h.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "template<typename X > \fBTree\fP< X >::\fBTree\fP (Xdata)\fC [inline]\fP"
.PP
Définition à la ligne 12 du fichier Tree.h.
.SS "template<typename X > \fBTree\fP< X >::~\fBTree\fP ()\fC [inline]\fP"
.PP
Définition à la ligne 16 du fichier Tree.h.
.SH "Documentation des données membres"
.PP 
.SS "template<typename X > X \fBTree\fP< X >::\fB_data\fP\fC [protected]\fP"
.PP
Définition à la ligne 8 du fichier Tree.h.
.SS "template<typename X > \fBTree\fP* \fBTree\fP< X >::\fB_fils_droit\fP\fC [protected]\fP"
.PP
Définition à la ligne 10 du fichier Tree.h.
.SS "template<typename X > \fBTree\fP* \fBTree\fP< X >::\fB_fils_gauche\fP\fC [protected]\fP"
.PP
Définition à la ligne 9 du fichier Tree.h.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Dr.Robotnik Mean Bean Machine à partir du code source.
